Add check for specific occurrence against form filter
Indicia-Team/client_helpers pull request #107
Opened 2020-07-20 14:39 UTC by burkmarr

Addresses part of issue 813. This addresses issue where non-moth records added via iRecord app cannot be edited using the iRecord form because a filter is set on that to only allow moth taxa. A check is added to dynamic_sample_occurrence.php to see if an occurrence ID is specified in URL. If it is and it does not pass the taxon filters specified on the form, it turns the filters off.

2020-07-20 14:47 UTC, johnvanbreda requested changes
I'm not sure I like the idea of making 2 extra web service hits to do this. The code calls a load_existing_record method later which means the taxa_taxon_list_id could be checked against the filter later?
Also the filter may not use a list of taxa_taxon_list_ids if the taxon_filter_field defines something else to filter on.
I think this we be better refactored into a small separate method rather than part of a much bigger one.

2020-07-20 15:11 UTC, burkmarr commented
Okay I will think again.

2020-07-21 09:11 UTC, burkmarr commented
@johnvanbreda - I don't understand what you mean by this:

> the filter may not use a list of taxa_taxon_list_ids if the taxon_filter_field defines something else to filter on

The code I wrote uses whatever field is specified, e.g. a taxon group, and applies both this filter plus a filter on the occurrence records taxa_taxon_list_id. And if that query returns zero records, then the filter, whatever it is, is not compatible with the taxon of the occurrence. Does that make sense?

2020-07-21 09:29 UTC, johnvanbreda commented
> the filter may not use a list of taxa_taxon_list_ids if the taxon_filter_field defines something else to filter on

Sorry - I see what the code is doing now - you can ignore this statement.

2020-07-31 10:59 UTC, burkmarr commented
@johnvanbreda - I've moved the check to the getEntity function. It kicks in after the taxa_taxon_list_id is retrieved in order to get the sample ID for species grids. So it just makes a single extra web service call to see if the taxon passes the filter criterion if set.

2020-07-31 12:51 UTC, merged